module.exports = {
  mode: "jit",
  purge: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      transitionProperty: {
        "height": "height",
        "width": "width",
        "opacity": "opacity",
        "color": "color",
        "background-color": "background-color",
      },
      transitionDuration: {
        "250": "250ms",
        "500": "500ms",
        "1000": "1000ms",
      },
      transitionTimingFunction: {
        "in": "ease-in",
        "out": "ease-out",
        "in-out": "ease-in-out",
      },
      transitionDelay: {
        "0": "0ms",
        "100": "100ms",
        "500": "500ms",
      },
    },
    colors: {
      "white-theme-000": "#ffffff",
      "white-theme-001": "#f7f6f3",
      "white-theme-002": "#eeede6",
      "white-theme-003": "#e6e4da",
      "white-theme-004": "#dddbcd",
      "white-theme-005": "#d5d2c1",
      "white-theme-006": "#ccc9b5",
      "white-theme-007": "#c4c0a8",
      "white-theme-008": "#bbb79c",
      "white-theme-009": "#b3ae8f",
      "white-theme-010": "#aaa583",
      "black-theme-001": "#b4b4b4",
      "black-theme-002": "#969696",
      "black-theme-003": "#6e6e6e",
      "black-theme-004": "#464646",
      "black-theme-005": "#1e1e1e",
      "black-theme-006": "#000000",
      "buttonn-red": "#EBBFCA",
      "buttonn-blue": "#96C5F0",
      "buttonn-neutral": "#CCD1BD",
    },
  },
  plugins: [],
};
